src/desock.c
I have run into applications using the accept4() function. This quick patch allows it to be intercepted.
=> Added accept4()

src/desock.c
This reorders the check that the socket is AF_INET or AF_INET6 to be intercepted to return sooner.
It also creates the stdin/out socket as protocol 0 to prevent invalid protocols being sent to the new socket.
=> Change AF_UNIX protocol to 0, return orig sooner

src/desock.c
This PR fixes a minor bug in `desock.c`. The bug is that, a correct `read` was being incorrectly flagged as EOF due to a mix-up between locals `n` and `total_n`. `total_n` should be used.
=> Bug fix: Change n to total_n post read syscall

src/desock.c
The modified accept function will fill the "addr struct" (passed as argument) with a random address as the peer socket. This change is tested with and only with nginx, which may not be well fitted with other programs.
=> Fill the peer's addr struct passed to accept

README.md
If the CFLAGS=-m32 is specified after the `make` command, the command is used exactly as specified on the command line; things like `CFLAGS+=-lpthread` will not work. By putting the variable before the `make` command, the correct extra CFLAGS options were added from the command line. This was tested on Ubuntu 14.04 64 bit while compiling 32 bit shared objects.
=> Move CFLAGS variables in README before the make command

README.md, src/Makefile, src/crazyrealloc.c, tests/Makefile, tests/realloc.c
People sometimes forget to check the return value of `realloc()`, assuming that there is space after their memory chunks such that expanding is not an issue. However this is not always the case and can lead to double-frees, use-after-frees etc.
Example code:
```c
char *s = malloc((size_t)10);
realloc(s, (size_t)15);
free(s); // <- potential double free 
```
This would result in a double free if `realloc()` moved the memory, and therefore `free()`d `s` afterwards internally before returning execution.
`crazyrealloc.c` ensures that memory is _always_ moved around, such that it's easier to detect bugs as the one described here.
=> crazyrealloc.c: force realloc() to move memory around

src/desleep.c, tests/Makefile, tests/sleep.c
* Added nanosleep (#38)
* Added tests for all sleep variations
```
> time ./tests/sleep                                                        
./tests/sleep  0,00s user 0,00s system 0% cpu 3,509 total
> time PREENY_DEBUG=1 LD_PRELOAD=./x86_64-linux-gnu/desleep.so ./tests/sleep
+++ Just spared you 1 seconds!
+++ Just spared you 1000000 microseconds!
+++ Just spared you 1 seconds and 500000000 nanoseconds!
PREENY_DEBUG=1 LD_PRELOAD=./x86_64-linux-gnu/desleep.so ./tests/sleep  0,00s user 0,00s system 63% cpu 0,001 total
```
=> Added tests to sleep, added nanosleep

README.md, src/decookie.c
A new module to dump the generated stack cookie on startup. Good for finding offsets in memory leaks.
Based on this article: https://www.elttam.com.au/blog/playing-with-canaries/
Based on this code: https://github.com/elttam/canary-fun/blob/master/read_canary.c
```
PREENY_INFO=1 LD_PRELOAD=./x86_64-linux-gnu/decookie.so ./tests/hello 
--- Found canary: 0x2ae8dc00
Hello world!
```
=> decookie.so: Dump stack cookie on startup

src/mallocwatch.c
printf() calls malloc() internally which means that mallocwatch with info printout creates an infinite recursion. This patch fixes https://github.com/zardus/preeny/issues/45 however this is not a thread safe solution.
=> Don't recurse mallocwatch on printf

src/getcanary.c
This fixes a warning while building preeny.
=> Declare preeny_logging_init before using it

tests/.gitignore
Without this gitignore, a simple `make` produced uncommitted changes.
=> gitignore: ignore test binaries

Makefile, README.md, src/Makefile
After these changes, all of the following now work correctly and produce a different target triple (in particular, compiling 32 bit on 64 bit host will put outputs into `i386-pc-linux-gnu`):
```
$ make # compiles normally
$ make -i ARCH=i386 # compiles for 32 bit x86, uses -m32 if host is x86_64
$ make -i CC=aarch64-linux-gnu-gcc # compiles for aarch64
$ make -i MACHINE=aarch64-linux-gnu # same as above
```
=> Better support for cross-compiling to 32 bit

src/Makefile, src/desock.c, src/desock_dup.c, src/ensock.c, src/eofkiller.c, src/patch.c, tests/realloc.c
This enables and fixes some _essential_ warnings like `Wreturn-type`.
With this commit `preeny` should still build without warnings.
=> Enable -Wall and clean up warnings

src/setcanary.c
`cmake-build-multiarch.sh` fails for `setcanary` for x86. Adding the support for x86 similar to what `getcanary` does.
=> Added support for x86 in setcanary like getcanary

README.md, src/getcanary.c, src/setcanary.c
As discussed in #54 
Stack canary is stored at `__stack_chk_guard` in arm. A simple load should do the trick.
Also fixing #56 by adding `libseccomp` dependency in README
=> Adding ARM support for getcanary

src/setcanary.c
As discussed in #54 I have added support for arm in setcanary. I have tested it on a raspberry pi.
```bash
pi@exos-pi:~ $ head -n 40 z.c
#include <stdio.h>
#include <stdint.h>
#ifdef __x86_64__
#define canary_t     uint64_t
#define INSN_READ    "movq %%fs:0x28, %0;"
#define FMT          "Found canary: %#lx\n"
#elif __i386__
#define canary_t     uint32_t
#define INSN_READ    "movl %%gs:0x14, %0;"
#define FMT          "Found canary: %#x\n"
#elif __arm__
#define canary_t     uint32_t
#define INSN_READ    "ldr r0, =__stack_chk_guard; ldr r0, [r0]; mov %0, r0;"
#define FMT          "Found canary: %#x\n"
#endif
canary_t read_canary()
{
canary_t val = 0;
__asm__(INSN_READ
: "=r"(val)
:
:);
return val;
}
int main(int argc, char **argv)
{
printf(FMT, read_canary());
return 0;
}
pi@exos-pi:~ $ gcc …
```
=> Adding support for arm in setcanary

src/mallocwatch.c
Fixes #59
Verify if `original_malloc` was actually resolved before calling it. If not, just call `preeny_mallocwatch_orig` to get it resolved. Technically `free` and `realloc` would never be called in a scenario like that but added just in case.
=> Adding check if dlsym was called before calling malloc+free family.

src/eofkiller.c
Hello!
```
{standard input}: Assembler messages:
{standard input}:496: Error: symbol __isoc99_scanf is already defined
{standard input}:622: Error: symbol __isoc99_fscanf is already defined
make[2]: *** [CMakeFiles/eofkiller.dir/build.make:63: CMakeFiles/eofkiller.dir/src/eofkiller.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:480: CMakeFiles/eofkiller.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```
Fix for Arch Linux build.
Thanks in advance!
=> eofkiller.c: build fix

src/mallocwatch.c
This makes indentation match the actual code flow, and fixes warnings given by gcc during compilation.  (Warnings are from -Wmisleading-indentation)
=> Fix indentation warnings

src/detime.c, test/.gitignore, test/Makefile, test/time.c
> ./test/time 
Time: 1572342926
Time: 1572342926.702952
TZ: -0 min, DST: 0
> LD_PRELOAD=./x86_64-linux-gnu/detime.so ./test/time 
Time: 0
Time: 0.0
TZ: -0 min, DST: 0
> LD_PRELOAD=./x86_64-linux-gnu/detime.so PREENY_DEBUG=1 TV_SEC=10 TV_USEC=100 TZ_MINWEST=3 TZ_DSTTIME=1 ./test/time
+++ time frozen at 0
Time: 0
+++ gettimeofday frozen at 10.100
+++ gettimeofday tz frozen at -3 minm, DST: 100
Time: 10.100
TZ: -3 min, DST: 1
=> Added gettimeofday() to detime.so

test/time.c
GCC 9 was complaining with the following
```
time.c: In function ‘main’:
time.c:11:17: warning: format ‘%d’ expects argument of type ‘int’, but argument 2 has type ‘time_t’ {aka ‘long int’} [-Wformat=]
11 |  printf("Time: %d\n", time(0));
|                ~^     ~~~~~~~
|                 |     |
|                 int   time_t {aka long int}
|                %ld
```
=> Fix compilation warning

src/desock.c
This signals the EOF to the receiving side.  This enhances the support discussed in #15.
=> Shutdown on EOF from stdin

src/desock.c
Fuzzing a single-threaded poll/epoll-based network server using AFL++
did not work because the server would call accept(2) again before
processing the first connection and would therefore instantly exit.
=> desock: exit on shutdown of accepted socket, not on 2nd accept

src/detime.c
There's a dummy `tv->tv_usec` arg while a call to `preeny_debug`
=> detime: remove a dummy arg

CMakeLists.txt, README.md, src/Makefile, src/setstdin.c, test/Makefile, test/run_tests.sh, test/setstdin_fread.c, test/setstdin_getc.c, test/setstdin_read.c
setstdin a library that allow to provide binary with alternative STDIN data by substituting `read`, `fread`, `fgetc`, `getc` and `getchar` calls
=> setstdin a library that allow to provide binary with alternative STDIN data

CMakeLists.txt, README.md, src/Makefile, src/nowrite.c, test/Makefile, test/nowrite.c, test/run_tests.sh
Forces `open` to open files in readonly mode. This prevents chaos when fuzzing binaries that unpack archives.
Binaries may still modify the FS with `unlink`/`mkdir`/... but open is a good start I guess :stuck_out_tongue_winking_eye:
=> Add nowrite
